CREATE TABLE transfer AS 
    SELECT 
        id, 
        BTRIM(marca) AS marca,
        BTRIM(modelo) AS modelo,
        BTRIM(mod) AS mod,
        BTRIM(body_type) AS body_type,
        BTRIM(portas) AS portas,
        BTRIM(bancos) AS bancos,
        BTRIM(bagagem) AS bagagem,
        BTRIM(combustivel) AS combustivel,
        BTRIM(sistema_combustivel) AS sistema_combustivel,
        BTRIM(tipo_motor) AS tipo_motor,
        BTRIM(posicao_motor) AS posicao_motor,
        BTRIM(capacidade_motor) AS capacidade_motor,
        BTRIM(cylinders) AS cylinders,
        BTRIM(power_out) AS power_out,
        BTRIM(aceleracao) AS aceleracao,
        BTRIM(velocidade_max) AS velocidade_max,
        BTRIM(rodas_motrizes) AS rodas_motrizes,
        BTRIM(tipo_direcao) AS tipo_direcao,
        BTRIM(gear_box) AS gear_box,
        BTRIM(comprimento) AS comprimento,
        BTRIM(largura) AS largura,
        BTRIM(altura) AS altura,
        BTRIM(peso) AS peso,
        BTRIM(wheel_base) AS wheel_base,
        BTRIM(suspencao_frontal) AS suspencao_frontal,
        BTRIM(suspencao_traseira) AS suspencao_traseira,
        BTRIM(freios_frontais) AS freios_frontais,
        BTRIM(freios_traseiros) AS freios_traseiros,
        BTRIM(pneus_frontais) AS pneus_frontais,
        BTRIM(pneus_traseiros) AS pneus_traseiros,
        BTRIM(fuel_urban) AS fuel_urban,
        BTRIM(fuel_extra_urban) AS fuel_extra_urban,
        BTRIM(fuel_combined) AS fuel_combined,
        BTRIM(volume_tanque) AS volume_tanque,
        img 
    FROM cars;

