CREATE TABLE transfer AS 
    SELECT 
        id_carro AS id, 
        brand AS marca,
        model AS modelo,
        modification AS mod,
        doors AS body_type,
        seats AS portas,
        luggage AS bancos,
        fuel_type AS bagagem,
        fuel_system AS combustivel,
        engine_type AS sistema_combustivel,
        engine_position AS tipo_motor,
        engine_capacity AS posicao_motor,
        cylinders AS capacidade_motor,
        power_out AS cylinders,
        torque AS power_out,
        acceleration AS aceleracao,
        max_speed AS velocidade_max,
        drive_weels AS rodas_motrizes,
        steering_type AS tipo_direcao,
        gear_box,
        length AS comprimento,
        width AS largura,
        height AS altura,
        weight AS peso,
        wheel_base,
        front_suspension AS suspensao_frontal,
        rear_suspension AS suspensao_traseira,
        front_brakers AS freios_frontais,
        rear_brakers AS freios_traseiros,
        front_tires AS pneus_dianteiros,
        rear_tires AS pneus_traseiros,
        fuel_urban,
        fuel_extra_urban,
        fuel_combined,
        fuel_volume AS volume_tanque,
        img 
    FROM cars;

