CREATE DATABASE car_search;
\c car_search
CREATE TABLE all_cars(
    id_carro VARCHAR PRIMARY KEY,
    brand VARCHAR NOT NULL,
    model VARCHAR NOT NULL,
    modification VARCHAR NOT NULL,
    bodytype VARCHAR,
    doors INT,
    seats INT,
    luggage VARCHAR,
    fuel_type VARCHAR,
    fuel_system VARCHAR,
    engine_type VARCHAR,
    engine_position VARCHAR,
    engine_capacity INT,
    cylinders VARCHAR,
    power_out VARCHAR,
    torque VARCHAR,
    acceleration REAL, 
    max_speed REAL,
    drive_weels VARCHAR,
    steering_type VARCHAR,
    gear_box VARCHAR,
    length INT,
    width INT,
    height INT,
    weight VARCHAR,
    wheel_base INT,
    front_suspension VARCHAR,
    rear_suspension VARCHAR,
    front_brakers VARCHAR,
    rear_brakers VARCHAR,
    front_tires VARCHAR,
    rear_tires VARCHAR,
    fuel_urban VARCHAR,
    fuel_extra_urban VARCHAR,
    fuel_combined VARCHAR,
    co2_emissions VARCHAR,
    fuel_volume INT,
    img VARCHAR
);